name = "fixbluesky"
main = "src/index.ts"
compatibility_date = "2023-01-01"

workers_dev = false
route = { pattern = "bskyx.app/*", zone_name = "bskyx.app" }

[vars]
BSKY_SERVICE_URL="https://bsky.social/"
FIXBLUESKY_APP_DOMAIN="bskyx.app"
